yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts, name='group_list'
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('groups/', views.groups, name='groups'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/comment.html
{% load thumbnail %}
{% load user_filters %}

<article>
        {% if user.is_authenticated %}
          <div class="card my-4 text-light bg-secondary">
          <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3"
                {% if field.field.required %}
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-warning">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

                <button type="submit" class="btn btn-success">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}" class="text-success">
                  {{ comment.author.username }}
                </a>
              </h5>
                <li>
                  Опубликован: {{ comment.created|date:"d E Y" }}
                </li>


              {% thumbnail comment.image "x750" as im %}
              <img src="{{ im.url }}">
            {% endthumbnail %}
              <p>
                {{ comment.text|linebreaks }}
              </p>
            </div>
          </div>
        {% endfor %}
      </article>

yatube/templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<style>
  .navbar-light .nav-link {
    color: Ivory !important;
  }
  .nav-pills > li > a.active {
    background-color: DimGrey !important;
}
</style>
{% with request.resolver_match.view_name as view_name %}
  <header>
    <nav class="navbar navbar-light" style="background-color: DarkSlateGrey">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:Ivory">Ya</span>tube
        </a>
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a
              class="nav-link
                {% if view_name == 'posts:index' %}
                  active
                {% endif %}"
                href="{% url 'posts:index' %}"
              >
            Главная
            </a>
          </li><li class="nav-item">
            <a
              class="nav-link
                {% if view_name == 'posts:groups' %}
                  active
                {% endif %}"
                href="{% url 'posts:groups' %}"
              >
            Группы
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'about:author' %}
                active
              {% endif %}"
              href="{% url 'about:author' %}"
            >
         Об авторе
       </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'about:tech' %}
                active
              {% endif %}"
              href="{% url 'about:tech' %}"
              >
              Технологии
            </a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link
              {% if view_name  == 'posts:post_create' %}
                  active
              {% endif %}"
                href="{% url 'posts:post_create' %}"
              >
                Новая запись
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'users:login' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li class="nav-item navbar-text">
              <a href="{% url 'posts:profile' request.user %}" class="text-light">Пользователь: {{ request.user }}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link " href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
{% endwith %}

yatube/templates/includes/paginator.html
<style>
  .pagination > li > a
  {
      background-color: FloralWhite;
      color: #5A4181;
  }

  .pagination > li > a:focus,
  .pagination > li > a:hover,
  .pagination > li > span:focus,
  .pagination > li > span:hover
  {
      color: #5a5a5a;
      background-color: #eee;
      border-color: #ddd;
  }

  .pagination > .active > a
  {
      color: white;
      background-color: #5A4181 !Important;
      border: solid 1px #5A4181 !Important;
  }

  .pagination > .active > a:hover
  {
      background-color: #5A4181 !Important;
      border: solid 1px #5A4181;
  }
</style>
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/single_post.html
{% load thumbnail %}
  <article>
    <ul>
      {% if show_author_link %}
        <li>
          <a href="{% url 'posts:profile' post.author %}" class="text-success">Автор: {{ post.author.get_full_name }}</a>
        </li>
      {% endif %}
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "x750" as im %}
      <img src="{{ im.url }}">
    {% endthumbnail %}


    <p>
      {{ post.text|linebreaks }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="text-success">Подробнее</a>
    {% if show_group_link and post.group %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}" class="text-success">{{ post.group.title }}</a></p>
    {% endif %}
  </article>
  {% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  {% with request.resolver_match.view_name as view_name %}
  <style>
    .nav-link {
      color: DarkGrey !important;
    }
    .nav-item {
      font-size: 15px;
      font-family: sans-serif;
    }
    .nav-pills > li > a.active {
      background-color: DarkSlateGrey !important;
  }
  </style>
    <div class="row my-3">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a
            class="nav-link
              {% if view_name == 'posts:index' %}
                active
              {% endif %}"
              href="{% url 'posts:index' %}" class="text-success"
            >
          Все авторы
          </a>
        </li>
        <li class="nav-item">
          <a
             class="nav-link
              {% if view_name == 'posts:follow_index' %}
               active
              {% endif %}"
              href="{% url 'posts:follow_index' %}" class="text-success"
            >
          Избранные авторы
          </a>
        </li>
      </ul>
    </div>
  {% endwith %}
{% endif %}