yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts, name='group_list'
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('groups/', views.groups, name='groups'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Задает название, описание группы, ссылку в адресной строке"""
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'название группы'

    def __str__(self):
        return f' {self.title}'


class Post(models.Model):
    """Задает текст поста, дату публикации, автора и группу"""
    text = models.TextField(
        verbose_name='Содержание записи',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Название группы',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    """
    Ссылка на пост и автора комментария,
    текст комментария, дата и время комментария.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Под каким постом оставлен комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        help_text='Автор отображается на сайте'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Обязательное поле, не должно быть пустым'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        help_text='Дата публикации',
        auto_now_add=True
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'Комментарии к постам'

    def __str__(self):
        return self.text


class Follow(models.Model):
    """Подписка пользователя на автора."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name_plural = 'Подписки на авторов'

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите какой-нибудь текст, ну пожалуйста 😥')
        self.fields['group'].empty_label = (
            'Нажмите сюда, чтобы выбрать группу')

    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        labels = {
            'text': 'Пост:',
            'group': 'Группа',
            'image': 'Изображение',
        }
        help_texts = {
            'text': 'Напишите пост и нажмите "Добавить"',
            'group': 'Выбирать группу не обязательно',
            'image': 'Вы можете добавить изображение.',
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Ваш комментарий')

    class Meta:
        model = Comment
        fields = ('text', 'image',)
        labels = {
            'text': 'Комментарий:',
            'image': 'Изображение',
        }
        help_texts = {
            'text': 'Напишите комментарий и нажмите "Добавить"',
            'image': 'Вы можете добавить изображение.',
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import paginator_util

User = get_user_model()


@cache_page(20)
@vary_on_cookie
def index(request):
    """Шаблон главной страницы."""
    template = 'posts/index.html'
    page_obj = paginator_util(Post.objects.all(), request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Шаблон страницы группы."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginator_util(group.posts.all(), request)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    """Шаблон страницы пользователя."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author, user=request.user,
    ).exists()
    page_obj = paginator_util(author.posts.all(), request)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Шаблон страницы поста."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Шаблон страницы новой записи."""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Шаблон страницы редактирования записи."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True, 'post': post}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Шаблон нового комментария."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post.pk)
    return redirect('posts:post_detail', post_id=post_id, form=form)


@login_required
def follow_index(request):
    """Шаблон страницы подписок."""
    template = 'posts/follow.html'
    page_obj = paginator_util(
        Post.objects.filter(author__following__user=request.user), request
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Шаблон профиля автора для подписки."""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
        return redirect('posts:profile', username)
    return redirect(template, username=author.username)


@login_required
def profile_unfollow(request, username):
    """Шаблон профиля автора для отписки."""
    Follow.objects.filter(
        user=request.user, author=get_object_or_404(User, username=username)
    ).delete()
    return redirect('posts:profile', username)


def groups(request):
    """Шаблон страницы списка групп."""
    template = 'posts/groups.html'
    page_obj = paginator_util(Group.objects.all(), request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} Новый пост {% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card text-light bg-secondary">
      <div class="card-header">
        {% if is_edit %}
          Редактировать запись
        {% else %}
          Добавить запись
        {% endif %}
      </div>
        {% include 'includes/errors.html' %}
          <form method="post" enctype="multipart/form-data" action="
            {% if is_edit %}
              {% url 'posts:post_edit' post.pk %}
            {% else %}
              {% url 'posts:post_create' %}{% endif %}"
          >
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-warning">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn-warning">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}
{% block content %}
<style>
  h1 {
    margin: 0;
    padding: 0;
    position: absolute;
    left: 50%;
    top: 11%;
    transform: translate(-50%, -50%);
    font-family: 'Roboto Slab', serif;
    text-transform: uppercase;
    color: DarkSlateGrey;
    font-size: 64px;
  }

  h1:before {
    content: attr(data-text);
    position: absolute;
    top: 0;
    left: 0;
    transform-origin: bottom;
    transform: rotateX(180deg);
    line-height: 1em;
    background: linear-gradient(0deg, DarkSlateGray 0, rgba(255, 255, 255, 0) 80%);
    -webkit-background-clip: text;
    color: rgba(0, 0, 0, 0);
    opacity: 0.8;
  }
</style>
{% include 'includes/switcher.html' %}
  <h1 data-text="Избранные авторы">Избранные авторы</h1>
  {% for post in page_obj %}
    {% include 'includes/single_post.html' with show_author_link=True show_group_link=True %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %}
    {{ group.title }}
  {% endblock %}
  {% block content %}
  <style>
    h1 {
      margin: 0;
      padding: 0;
      position: absolute;
      left: 50%;
      top: 11%;
      transform: translate(-50%, -50%);
      font-family: 'Roboto Slab', serif;
      text-transform: uppercase;
      color: DarkSlateGrey;
      font-size: 44px;
    }

    h1:before {
      content: attr(data-text);
      position: absolute;
      top: 0;
      left: 0;
      transform-origin: bottom;
      transform: rotateX(180deg);
      line-height: 1em;
      background: linear-gradient(0deg, DarkSlateGray 0, rgba(255, 255, 255, 0) 80%);
      -webkit-background-clip: text;
      color: rgba(0, 0, 0, 0);
      opacity: 0.8;
    }
  </style>
    <h1 data-text="{{ group.title }}"> {{ group.title }}</h1>
    <p>
      {{ group.description|linebreaks }}
    </p>
    {% for post in page_obj %}
     {% include 'includes/single_post.html' with show_author_link=True show_group_link=False %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/groups.html
{% extends 'base.html' %}
  {% block title %}
    Список групп
  {% endblock %}
  {% block content %}
  <style>
    h1 {
      margin: 0;
      padding: 0;
      position: absolute;
      left: 50%;
      top: 11%;
      transform: translate(-50%, -50%);
      font-family: 'Roboto Slab', serif;
      text-transform: uppercase;
      color: DarkSlateGrey;
      font-size: 44px;
    }

    h1:before {
      content: attr(data-text);
      position: absolute;
      top: 0;
      left: 0;
      transform-origin: bottom;
      transform: rotateX(180deg);
      line-height: 1em;
      background: linear-gradient(0deg, DarkSlateGray 0, rgba(255, 255, 255, 0) 80%);
      -webkit-background-clip: text;
      color: rgba(0, 0, 0, 0);
      opacity: 0.8;
    }
  </style>
    <h1 data-text="Список всех групп"> Список всех групп</h1>
    {% for group in page_obj %}
      <article>
        <ul>
            <a href="{% url 'posts:group_list' group.slug %}" class="text-success">{{ group.title }}</a>
        </ul>
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
<style>
  h1 {
    margin: 0;
    padding: 0;
    position: absolute;
    left: 50%;
    top: 11%;
    transform: translate(-50%, -50%);
    font-family: 'Roboto Slab', serif;
    text-transform: uppercase;
    color: DarkSlateGrey;
    font-size: 64px;
  }

  h1:before {
    content: attr(data-text);
    position: absolute;
    top: 0;
    left: 0;
    transform-origin: bottom;
    transform: rotateX(180deg);
    line-height: 1em;
    background: linear-gradient(0deg, DarkSlateGray 0, rgba(255, 255, 255, 0) 80%);
    -webkit-background-clip: text;
    color: rgba(0, 0, 0, 0);
    opacity: 0.8;
  }
</style>
{% include 'includes/switcher.html' %}
<h1 data-text="YaTube">YaTube</h1>
  {% for post in page_obj %}
    {% include 'includes/single_post.html' with show_author_link=True show_group_link=True %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|slice:30 }}
{% endblock %}
{% block content %}
  <div class="row text-dark">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item text-light bg-dark">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item text-light bg-secondary">
          Группа: {{ group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}" class="text-light">Все записи группы</a>
        </li>
        {% endif %}
        <li class="list-group-item text-light bg-secondary">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center text-light bg-secondary">
          Количество публикаций: <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item text-light bg-secondary">
          <a href="{% url 'posts:profile' post.author %}" class="text-light">Все записи пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "x600" as im %}
        <img src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if user == post.author %}
        <a class="btn btn-secondary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать запись
        </a>
      {% endif %}
      {% include 'includes/comment.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Страница пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
<style>
  h1 {
    margin: 0;
    padding: 0;
    position: absolute;
    left: 50%;
    top: 11%;
    transform: translate(-50%, -50%);
    font-family: 'Roboto Slab', serif;
    text-transform: uppercase;
    color: DarkSlateGrey;
    font-size: 44px;
  }

  h1:before {
    content: attr(data-text);
    position: absolute;
    top: 0;
    left: 0;
    transform-origin: bottom;
    transform: rotateX(180deg);
    line-height: 1em;
    background: linear-gradient(0deg, DarkSlateGray 0, rgba(255, 255, 255, 0) 80%);
    -webkit-background-clip: text;
    color: rgba(0, 0, 0, 0);
    opacity: 0.8;
  }
</style>
  <div class="container py-5">
    <div class="mb-5">
      <h1 data-text="{{ author.get_full_name }}">{{ author.get_full_name }}</h1>
      <h3>Количество публикаций: {{ author.posts.count }}</h3>
        {% if user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-secondary"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-dark"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                Подписаться
            </a>
          {% endif %}
        {% endif %}
      {% for post in page_obj %}
       {% include 'includes/single_post.html' with show_author_link=False show_group_link=True %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </div>
  </div>
{% endblock %}